title: GDHS Resource Manual
description: A website for documenting the processes and decisions that go into creating the MSU Global DH Symposium
theme: just-the-docs

url: https://global-dh-symposium-documentation.github.io/resource_manual/

aux_links:
  #Template Repository: https://github.com/Global-DH-Symposium-Documentation/resource_manual
  Global DH Symposium: https://msuglobaldh.org/